version: '3.2'

services:
  db:
      image: postgres:14
      restart: always
      container_name: db
      env_file:
        - .env
      ports:
          - "5434:5432"
      networks:
          - connection
  backend:
      image: python:3.8
      container_name: backend
      build: ./library_back
      restart: always
      ports:
          - '8000:8000'
      depends_on:
          - db
      env_file:
        - .env
      networks:
          - connection
      command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
      image: node:14
      container_name: frontend
      build: ./library_front
      ports:
          - '3000:3000'
      restart: always
      depends_on:
          - backend
      networks:
          - connection
  
  nginx:
      image: nginx:1.15-alpine
      container_name: nginx
      restart: always
      ports:
          - '80:80'
      volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
          - frontend
      networks:
          - connection

networks:
  connection:
      driver: bridge