version: '3.9'

services:
  db: 
    image: postgres:13.2
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432

    
volumes:
  db: