version: '3.9'

services:
  db: 
    image: postgres:13.2
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: library_db
      POSTGRES_Host: postgresql_db
      POSTGRES_PORT: 5432
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 "
    ports:
      - 8000:8000
    
volumes:
  db: