version: '3.9'

services:
  db: 
    image: postgres:13.2
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 "
    ports:
      - 8000:8000
    
volumes:
  db: